components:
  securitySchemes: {}
info:
  title: ics-api
  version: 1.0.0
  description: A potent API created for digital campaign marketing
  license:
    name: UNLICENSED
  contact:
    name: 'Oscar '
    email: oscar@ticketsocket.com
openapi: 3.0.0
paths:
  '/test/{testId}':
    $ref: 'paths/test@{testId}.yaml'
  /test:
    $ref: paths/test.yaml
  /webhooks/events:
    $ref: paths/webhooks@events.yaml
  '/webhooks/campaign/{campaignId}':
    $ref: 'paths/webhooks@campaign@{campaignId}.yaml'
  '/webhooks/campaign/{campaignId}/subscription/{webhookSubscriptionId}':
    $ref: >-
      paths/webhooks@campaign@{campaignId}@subscription@{webhookSubscriptionId}.yaml
  '/webhooks/campaign/{campaignId}/test':
    $ref: 'paths/webhooks@campaign@{campaignId}@test.yaml'
servers:
  - url: /app.icecreamsocial.io
