components:
  securitySchemes: {}
info:
  title: ics-api
  version: 1.0.0
  description: A potent API created for digital campaign marketing
  license:
    name: UNLICENSED
  contact:
    name: 'Oscar '
    email: oscar@ticketsocket.com
openapi: 3.0.0
paths:
  '/v2/affiliates/{affiliateId}':
    $ref: 'paths/v2@affiliates@{affiliateId}.yaml'
  /v2/affiliates/nested-affiliates:
    $ref: paths/v2@affiliates@nested-affiliates.yaml
  /v2/affiliates:
    $ref: paths/v2@affiliates.yaml
  /v2/auth/token:
    $ref: paths/v2@auth@token.yaml
  '/v2/clients/{clientId}':
    $ref: 'paths/v2@clients@{clientId}.yaml'
  /v2/clients/nested-clients:
    $ref: paths/v2@clients@nested-clients.yaml
  /v2/clients:
    $ref: paths/v2@clients.yaml
  '/v2/clients/regenPublicKey/{clientId}':
    $ref: 'paths/v2@clients@regenPublicKey@{clientId}.yaml'
  '/v2/client/campaigns/{campaignId}':
    $ref: 'paths/v2@client@campaigns@{campaignId}.yaml'
  '/v2/client/campaigns/{campaignId}/influencers':
    $ref: 'paths/v2@client@campaigns@{campaignId}@influencers.yaml'
  /v2/users:
    $ref: paths/v2@users.yaml
  /v2/users/nested-users:
    $ref: paths/v2@users@nested-users.yaml
  '/v2/users/{userId}':
    $ref: 'paths/v2@users@{userId}.yaml'
  /v2/users/stats-overview:
    $ref: paths/v2@users@stats-overview.yaml
  /v2/users/daily-stats:
    $ref: paths/v2@users@daily-stats.yaml
  /v2/webhooks/events:
    $ref: paths/v2@webhooks@events.yaml
  '/v2/webhooks/campaign/{campaignId}':
    $ref: 'paths/v2@webhooks@campaign@{campaignId}.yaml'
  '/v2/webhooks/campaign/{campaignId}/subscription/{webhookSubscriptionId}':
    $ref: >-
      paths/v2@webhooks@campaign@{campaignId}@subscription@{webhookSubscriptionId}.yaml
servers:
  - url: 'https://dev.icecreamsocial.io/api'
