components:
  securitySchemes: {}
info:
  title: ics-api
  version: 1.0.0
  description: A potent API created for digital campaign marketing
  license:
    name: UNLICENSED
  contact:
    name: 'Oscar '
    email: oscar@ticketsocket.com
openapi: 3.0.0
paths:
  /auth/token:
    $ref: paths/auth@token.yaml
  /webhooks/events:
    $ref: paths/webhooks@events.yaml
  '/webhooks/campaign/{campaignId}':
    $ref: 'paths/webhooks@campaign@{campaignId}.yaml'
  '/webhooks/campaign/{campaignId}/subscription/{webhookSubscriptionId}':
    $ref: >-
      paths/webhooks@campaign@{campaignId}@subscription@{webhookSubscriptionId}.yaml
servers:
  - url: 'https://dev.icecreamsocial.io/api/v2'
