components:
  securitySchemes: {}
info:
  title: ics-api
  version: 1.0.0
  description: A potent API created for digital campaign marketing
  license:
    name: UNLICENSED
  contact:
    name: 'Oscar '
    email: oscar@ticketsocket.com
openapi: 3.0.0
paths:
  /api/v2/auth/token:
    $ref: paths/api@v2@auth@token.yaml
  /api/v2/webhooks/events:
    $ref: paths/api@v2@webhooks@events.yaml
  '/api/v2/webhooks/campaign/{campaignId}':
    $ref: 'paths/api@v2@webhooks@campaign@{campaignId}.yaml'
  '/api/v2/webhooks/campaign/{campaignId}/subscription/{webhookSubscriptionId}':
    $ref: >-
      paths/api@v2@webhooks@campaign@{campaignId}@subscription@{webhookSubscriptionId}.yaml
servers:
  - url: 'https://app.icecreamsocial.io/api/v2'
