components:
  securitySchemes: {}
info:
  title: ics-api
  version: 1.0.0
  description: A potent API created for digital campaign marketing
  license:
    name: UNLICENSED
  contact:
    name: 'Oscar '
    email: oscar@ticketsocket.com
openapi: 3.0.0
paths:
  '/v2/affiliates/{affiliateId}':
    $ref: 'paths/v2@affiliates@{affiliateId}.yaml'
  /v2/affiliates/nested-affiliates:
    $ref: paths/v2@affiliates@nested-affiliates.yaml
  /v2/affiliates:
    $ref: paths/v2@affiliates.yaml
  /v2/auth/token:
    $ref: paths/v2@auth@token.yaml
  '/v2/campaigns/{campaignId}/influencers':
    $ref: 'paths/v2@campaigns@{campaignId}@influencers.yaml'
  '/v2/campaigns/{campaignId}/influencers/export':
    $ref: 'paths/v2@campaigns@{campaignId}@influencers@export.yaml'
  '/v2/campaigns/{campaignId}/influencers/{influencerId}':
    $ref: 'paths/v2@campaigns@{campaignId}@influencers@{influencerId}.yaml'
  '/v2/campaigns/{campaignId}/influencers/{influencerId}/processInfluencer':
    $ref: >-
      paths/v2@campaigns@{campaignId}@influencers@{influencerId}@processInfluencer.yaml
  '/v2/campaigns/{campaignId}/influencers/{influencerId}/invites':
    $ref: 'paths/v2@campaigns@{campaignId}@influencers@{influencerId}@invites.yaml'
  '/v2/campaigns/{campaignId}/influencers/{influencerId}/conversions':
    $ref: >-
      paths/v2@campaigns@{campaignId}@influencers@{influencerId}@conversions.yaml
  '/v2/campaigns/{campaignId}/influencers/{influencerId}/invites/{inviteId}':
    $ref: >-
      paths/v2@campaigns@{campaignId}@influencers@{influencerId}@invites@{inviteId}.yaml
  '/v2/campaigns/{campaignId}/influencers/{influencerId}/invites/{inviteId}/conversions':
    $ref: >-
      paths/v2@campaigns@{campaignId}@influencers@{influencerId}@invites@{inviteId}@conversions.yaml
  '/v2/campaigns/{campaignId}/influencers/{influencerId}/invites/influencedConversions':
    $ref: >-
      paths/v2@campaigns@{campaignId}@influencers@{influencerId}@invites@influencedConversions.yaml
  '/v2/campaigns/{campaignId}/influencers/{influencerId}/conversions/{conversionId}':
    $ref: >-
      paths/v2@campaigns@{campaignId}@influencers@{influencerId}@conversions@{conversionId}.yaml
  '/v2/campaigns/{campaignId}/influencers/{influencerId}/cardFlexRefund':
    $ref: >-
      paths/v2@campaigns@{campaignId}@influencers@{influencerId}@cardFlexRefund.yaml
  '/v2/campaigns/{campaignId}/influencers/{influencerId}/createManualConversion':
    $ref: >-
      paths/v2@campaigns@{campaignId}@influencers@{influencerId}@createManualConversion.yaml
  /v2/campaigns/issueSquareGiftCard:
    $ref: paths/v2@campaigns@issueSquareGiftCard.yaml
  /v2/campaigns/nested:
    $ref: paths/v2@campaigns@nested.yaml
  /v2/campaigns:
    $ref: paths/v2@campaigns.yaml
  '/v2/campaigns/{campaignId}':
    $ref: 'paths/v2@campaigns@{campaignId}.yaml'
  '/v2/campaigns/{campaignId}/conversions':
    $ref: 'paths/v2@campaigns@{campaignId}@conversions.yaml'
  '/v2/campaigns/{campaignId}/checkValidRefundGateway':
    $ref: 'paths/v2@campaigns@{campaignId}@checkValidRefundGateway.yaml'
  '/v2/campaigns/{campaignId}/checkInfluencerProcessing':
    $ref: 'paths/v2@campaigns@{campaignId}@checkInfluencerProcessing.yaml'
  '/v2/campaigns/{campaignId}/provider/{providerId}':
    $ref: 'paths/v2@campaigns@{campaignId}@provider@{providerId}.yaml'
  '/v2/clients/{clientId}':
    $ref: 'paths/v2@clients@{clientId}.yaml'
  /v2/clients/nested-clients:
    $ref: paths/v2@clients@nested-clients.yaml
  /v2/clients:
    $ref: paths/v2@clients.yaml
  '/v2/clients/regenPublicKey/{clientId}':
    $ref: 'paths/v2@clients@regenPublicKey@{clientId}.yaml'
  '/v2/client/campaigns/{campaignId}':
    $ref: 'paths/v2@client@campaigns@{campaignId}.yaml'
  '/v2/client/campaigns/{campaignId}/influencers':
    $ref: 'paths/v2@client@campaigns@{campaignId}@influencers.yaml'
  '/v2/client/campaigns/{campaignId}/influencers/{influencerId}/invites/fb':
    $ref: >-
      paths/v2@client@campaigns@{campaignId}@influencers@{influencerId}@invites@fb.yaml
  '/v2/client/campaigns/{campaignId}/influencers/{influencerId}/invites/generic':
    $ref: >-
      paths/v2@client@campaigns@{campaignId}@influencers@{influencerId}@invites@generic.yaml
  '/v2/client/campaigns/{campaignId}/influencers/{influencerId}/invites/gm':
    $ref: >-
      paths/v2@client@campaigns@{campaignId}@influencers@{influencerId}@invites@gm.yaml
  '/v2/client/campaigns/{campaignId}/email':
    $ref: 'paths/v2@client@campaigns@{campaignId}@email.yaml'
  '/v2/users/{userId}':
    $ref: 'paths/v2@users@{userId}.yaml'
  /v2/users:
    $ref: paths/v2@users.yaml
  /v2/users/nested-users:
    $ref: paths/v2@users@nested-users.yaml
  /v2/users/stats-overview:
    $ref: paths/v2@users@stats-overview.yaml
  /v2/users/daily-stats:
    $ref: paths/v2@users@daily-stats.yaml
  /v2/webhooks/events:
    $ref: paths/v2@webhooks@events.yaml
  '/v2/webhooks/campaign/{campaignId}':
    $ref: 'paths/v2@webhooks@campaign@{campaignId}.yaml'
  '/v2/webhooks/campaign/{campaignId}/subscription/{webhookSubscriptionId}':
    $ref: >-
      paths/v2@webhooks@campaign@{campaignId}@subscription@{webhookSubscriptionId}.yaml
servers:
  - url: 'https://dev.icecreamsocial.io/api'
