components:
  securitySchemes: {}
info:
  title: ics-api
  version: 1.0.0
  description: A potent API created for digital campaign marketing
  license:
    name: UNLICENSED
  contact:
    name: 'Oscar '
    email: oscar@ticketsocket.com
openapi: 3.0.0
paths:
  '/ap1/v2/test/{testId}':
    $ref: 'paths/ap1@v2@test@{testId}.yaml'
  /ap1/v2/test:
    $ref: paths/ap1@v2@test.yaml
  /ap1/v2/webhooks/events:
    $ref: paths/ap1@v2@webhooks@events.yaml
  '/ap1/v2/webhooks/campaign/{campaignId}':
    $ref: 'paths/ap1@v2@webhooks@campaign@{campaignId}.yaml'
  '/ap1/v2/webhooks/campaign/{campaignId}/subscription/{webhookSubscriptionId}':
    $ref: >-
      paths/ap1@v2@webhooks@campaign@{campaignId}@subscription@{webhookSubscriptionId}.yaml
  '/ap1/v2/webhooks/campaign/{campaignId}/test':
    $ref: 'paths/ap1@v2@webhooks@campaign@{campaignId}@test.yaml'
servers:
  - url: 'https://app.icecreamsocial.io/api/v2'
